<a href="https://colab.research.google.com/github/anuragpandey4/dl/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
import time
import math

# Check if GPU is available
print(f"PyTorch version: {torch.__version__}")
print(f"GPU available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU name: {torch.cuda.get_device_name(0)}")
else:
    print("⚠️ No GPU detected. Go to Runtime → Change runtime type → GPU")
    print("   (Some demos will still work, just slower)")

print("\n✅ Setup complete! Ready to go.")

PyTorch version: 2.11.0+cu128
GPU available: True
GPU name: Tesla T4

✅ Setup complete! Ready to go.


In [3]:
# A scalar (0D Tensor)
x = torch.tensor(5.0)
x

tensor(5.)

In [4]:
# A vector (1D Tensor)
v = torch.tensor([1.0, 2.0, 3.0])
v

tensor([1., 2., 3.])

In [5]:
# A matrix (2D Tensor)
m = torch.tensor([[1, 2], [3, 4]])
m

tensor([[1, 2],
        [3, 4]])

In [6]:
# A 3D tensor (e.g., Batch x Height x Width)
t = torch.zeros(2, 3, 4) # shape [2, 3, 4]
t

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
# Check shape — you'll do this ALL the time
print(t.shape)

torch.Size([2, 3, 4])


In [8]:
a = torch.randn(3,4)
b = torch.randn(4,5)

In [9]:
a @ b

tensor([[-0.8761, -2.4139,  3.5248, -0.8339, -2.9033],
        [-0.6077, -0.0815,  1.4870,  2.3056, -0.0219],
        [ 0.6775,  1.4089, -0.6070,  4.3729,  1.7176]])

In [10]:
x = torch.randn(8,3,768)

In [11]:
x.dim()

3

In [12]:
x = x.view(24,768)

In [13]:
x.dim()

2

In [14]:
x = torch.randn(8,12,3,64)

In [15]:
y = x.permute(0,2,1,3)

In [16]:
y.shape

torch.Size([8, 3, 12, 64])

# autograd

In [17]:
x = torch.tensor(3.0, requires_grad=True)

In [18]:
y = x ** 2 + 3

In [19]:
y.backward()

In [20]:
x.grad

tensor(6.)

In [21]:
# A scalar — just a number
scalar = torch.tensor(42.0)
print(f"Scalar: {scalar}")
print(f"  Shape: {scalar.shape}")      # torch.Size([])
print(f"  Dimensions: {scalar.dim()}")  # 0
print()

# A vector — a list of numbers
vector = torch.tensor([1.0, 2.0, 3.0, 4.0])
print(f"Vector: {vector}")
print(f"  Shape: {vector.shape}")      # torch.Size([4])
print(f"  Dimensions: {vector.dim()}")  # 1
print()

# A matrix — a grid of numbers
matrix = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])
print(f"Matrix:\n{matrix}")
print(f"  Shape: {matrix.shape}")      # torch.Size([2, 3])
print(f"  Dimensions: {matrix.dim()}")  # 2
print()

# A 3D tensor — a cube of numbers
tensor_3d = torch.zeros(2, 3, 4)
print(f"3D Tensor shape: {tensor_3d.shape}")    # [2, 3, 4]
print(f"  Dimensions: {tensor_3d.dim()}")        # 3
print()

# A 4D tensor — like a batch going through multi-head attention
tensor_4d = torch.zeros(8, 12, 3, 64)
print(f"4D Tensor shape: {tensor_4d.shape}")    # [8, 12, 3, 64]
print(f"  That's: 8 sentences × 12 heads × 3 tokens × 64 dims")

Scalar: 42.0
  Shape: torch.Size([])
  Dimensions: 0

Vector: tensor([1., 2., 3., 4.])
  Shape: torch.Size([4])
  Dimensions: 1

Matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])
  Shape: torch.Size([2, 3])
  Dimensions: 2

3D Tensor shape: torch.Size([2, 3, 4])
  Dimensions: 3

4D Tensor shape: torch.Size([8, 12, 3, 64])
  That's: 8 sentences × 12 heads × 3 tokens × 64 dims


In [22]:
# Zeros and ones
z = torch.zeros(3, 4)        # 3×4 matrix of zeros
o = torch.ones(2, 5)         # 2×5 matrix of ones

# Random (normal distribution) — this is how weights start!
r = torch.randn(3, 3)        # random values, mean=0, std=1
print("Random matrix (this is how neural network weights begin):")
print(r)
print()

# From a range
seq = torch.arange(0, 10)    # [0, 1, 2, ..., 9]
print(f"Sequence: {seq}")

# Linspace — evenly spaced
lin = torch.linspace(0, 1, 5)  # 5 values from 0 to 1
print(f"Linspace: {lin}")

Random matrix (this is how neural network weights begin):
tensor([[-0.0575, -0.3929, -2.2569],
        [ 0.0143,  1.6259, -0.5419],
        [-1.1261, -0.4478, -0.5916]])

Sequence: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Linspace: tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [23]:
# Real-world shapes in deep learning:
batch_size = 8
seq_len = 128
embed_dim = 768
num_heads = 12
head_dim = embed_dim // num_heads  # 64

# A batch of tokenized sentences
x = torch.randn(batch_size, seq_len, embed_dim)
print(f"Batch of sentences: {x.shape}")
print(f"  {batch_size} sentences, {seq_len} tokens each, {embed_dim} dimensions per token")
print()

# Reshape for multi-head attention
x_heads = x.view(batch_size, seq_len, num_heads, head_dim)
print(f"After splitting into heads: {x_heads.shape}")
print(f"  {batch_size} sentences, {seq_len} tokens, {num_heads} heads, {head_dim} dims per head")
print()

# Rearrange so heads come before tokens (needed for attention)
x_ready = x_heads.permute(0, 2, 1, 3)
print(f"After permute for attention: {x_ready.shape}")
print(f"  {batch_size} sentences, {num_heads} heads, {seq_len} tokens, {head_dim} dims")
print()
print("☝️ This is EXACTLY what happens inside every transformer!")

Batch of sentences: torch.Size([8, 128, 768])
  8 sentences, 128 tokens each, 768 dimensions per token

After splitting into heads: torch.Size([8, 128, 12, 64])
  8 sentences, 128 tokens, 12 heads, 64 dims per head

After permute for attention: torch.Size([8, 12, 128, 64])
  8 sentences, 12 heads, 128 tokens, 64 dims

☝️ This is EXACTLY what happens inside every transformer!


### 🛑 Try It Yourself
1. Create a tensor of shape `[4, 10, 512]` (4 sentences, 10 tokens, 512 dims)
2. Check its shape and number of dimensions
3. Reshape it to `[4, 10, 8, 64]` (split into 8 attention heads)
4. Permute it to `[4, 8, 10, 64]`

In [33]:
#1

x = torch.randn(4,10,512)

#2
print(x.shape)
print(x.dim())

#3
x = x.view(4,10,8,64)
print(x.shape)

#3
x = x.permute(0,2,1,3)
print(x.shape)


torch.Size([4, 10, 512])
3
torch.Size([4, 10, 8, 64])
torch.Size([4, 8, 10, 64])


# Matrix Magic — Transformations Visualized

In [37]:
# A vector pointing right
v = torch.tensor([1.0, 0.0])
print(f"Original vector: {v.tolist()}")

# Rotation matrix (90 degrees counterclockwise)
rotate_90 = torch.tensor([[0., -1.],
                           [1.,  0.]])

rotated = rotate_90 @ v
print(f"After 90° rotation: {rotated.tolist()}")

# Rotation matrix (45 degrees)
angle = math.radians(45)
rotate_45 = torch.tensor([[math.cos(angle), -math.sin(angle)],
                           [math.sin(angle),  math.cos(angle)]])

rotated_45 = rotate_45 @ v
print(f"After 45° rotation: [{rotated_45[0]:.3f}, {rotated_45[1]:.3f}]")

Original vector: [1.0, 0.0]
After 90° rotation: [0.0, 1.0]
After 45° rotation: [0.707, 0.707]


In [38]:
# Two similar vectors (pointing roughly the same way)
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([1.1, 1.9, 3.1])
print(f"Similar vectors dot product: {a @ b:.2f}")  # high!

# Two perpendicular vectors
c = torch.tensor([1.0, 0.0])
d = torch.tensor([0.0, 1.0])
print(f"Perpendicular dot product:   {c @ d:.2f}")  # zero!

# Two opposite vectors
e = torch.tensor([1.0, 2.0])
f = torch.tensor([-1.0, -2.0])
print(f"Opposite vectors dot product: {e @ f:.2f}")  # negative!

print()
print("☝️ This is EXACTLY what attention does:")
print("   Q · K = how much should this word attend to that word?")

Similar vectors dot product: 14.20
Perpendicular dot product:   0.00
Opposite vectors dot product: -5.00

☝️ This is EXACTLY what attention does:
   Q · K = how much should this word attend to that word?


In [42]:
# 3. Gradient accumulation — the gotcha
x = torch.tensor(3.0, requires_grad=True)


y1 = x ** 2
print(x.grad)
y1.backward()
print(f"After first backward: x.grad = {x.grad}")   # 6.0

y2 = x ** 2
y2.backward()
print(f"After second backward: x.grad = {x.grad}")  # 12.0! Accumulated!

# This is why we call zero_grad()
x.grad.zero_()
y3 = x ** 2
y3.backward()
print(f"After zero + backward: x.grad = {x.grad}")  # 6.0 — fresh!

None
After first backward: x.grad = 6.0
After second backward: x.grad = 12.0
After zero + backward: x.grad = 6.0


In [43]:
# Basic math — element-wise
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

print("Element-wise operations:")
print(f"  a + b = {a + b}")
print(f"  a * b = {a * b}")      # element-wise multiply
print(f"  a @ b = {a @ b}")      # dot product!
print()

# Broadcasting in action
matrix = torch.tensor([[1.0, 2.0, 3.0],
                        [4.0, 5.0, 6.0]])
bias = torch.tensor([10.0, 20.0, 30.0])

result = matrix + bias  # bias gets added to EVERY row
print("Broadcasting:")
print(f"  Matrix shape: {matrix.shape}")
print(f"  Bias shape:   {bias.shape}")
print(f"  Result:\n{result}")
print("  ☝️ Bias was added to both rows automatically!")
print()

# Useful operations
x = torch.randn(3, 4)
print(f"Random tensor:\n{x}\n")
print(f"  Mean:    {x.mean():.4f}")
print(f"  Std:     {x.std():.4f}")
print(f"  Max:     {x.max():.4f}")
print(f"  Argmax:  {x.argmax()} (index of largest element)")
print(f"  Softmax: {torch.softmax(x[0], dim=0)}")
print(f"  ☝️ Softmax turns values into probabilities (sums to 1)")

Element-wise operations:
  a + b = tensor([5., 7., 9.])
  a * b = tensor([ 4., 10., 18.])
  a @ b = 32.0

Broadcasting:
  Matrix shape: torch.Size([2, 3])
  Bias shape:   torch.Size([3])
  Result:
tensor([[11., 22., 33.],
        [14., 25., 36.]])
  ☝️ Bias was added to both rows automatically!

Random tensor:
tensor([[-0.9758,  0.5081,  0.0399,  0.4189],
        [ 0.5047, -0.6792,  0.3115, -0.4021],
        [ 0.5351, -1.6561,  1.1006,  0.1917]])

  Mean:    -0.0086
  Std:     0.7768
  Max:     1.1006
  Argmax:  10 (index of largest element)
  Softmax: tensor([0.0819, 0.3613, 0.2262, 0.3305])
  ☝️ Softmax turns values into probabilities (sums to 1)


In [44]:
# Simple: y = x² + 2x + 1, find dy/dx at x=3
x = torch.tensor(3.0, requires_grad=True)  # ← "track this!"

y = x**2 + 2*x + 1  # y = 9 + 6 + 1 = 16
print(f"x = {x.item()}")
print(f"y = x² + 2x + 1 = {y.item()}")

y.backward()  # ← compute ALL gradients

print(f"dy/dx = {x.grad.item()}")
print(f"Check: dy/dx = 2x + 2 = 2(3) + 2 = {2*3 + 2} ✓")
print()

x = 3.0
y = x² + 2x + 1 = 16.0
dy/dx = 8.0
Check: dy/dx = 2x + 2 = 2(3) + 2 = 8 ✓



In [45]:
x = torch.tensor(2.0, requires_grad=True)

# A more complex function
y = torch.sin(x) * torch.exp(x) + x**3

y.backward()

print(f"f(x) = sin(x) × eˣ + x³")
print(f"f(2) = {y.item():.4f}")
print(f"f'(2) = {x.grad.item():.4f}")
print()

# Verify numerically (finite difference)
h = 1e-5
x_val = 2.0
f_x = np.sin(x_val) * np.exp(x_val) + x_val**3
f_x_h = np.sin(x_val + h) * np.exp(x_val + h) + (x_val + h)**3
numerical_grad = (f_x_h - f_x) / h
print(f"Numerical check: {numerical_grad:.4f}")
print("☝️ They match! Autograd is correct no matter how complex the function.")

f(x) = sin(x) × eˣ + x³
f(2) = 14.7188
f'(2) = 15.6439

Numerical check: 15.6439
☝️ They match! Autograd is correct no matter how complex the function.


In [46]:
# This is what actually happens during training
W = torch.randn(3, 2, requires_grad=True)  # a weight matrix
x = torch.tensor([1.0, 0.5])                # input
target = torch.tensor([1.0, 0.0, 0.0])      # target output

# Forward pass
prediction = W @ x                    # matrix × vector
loss = ((prediction - target)**2).sum()  # MSE loss

print(f"Weight matrix W:\n{W.data}")
print(f"Input: {x}")
print(f"Prediction: {prediction.data}")
print(f"Target: {target}")
print(f"Loss: {loss.item():.4f}")
print()

# Backward pass — gradients for EVERY element of W
loss.backward()

print(f"Gradients for W (∂Loss/∂W):\n{W.grad}")
print()
print("☝️ PyTorch computed the gradient for all 6 weights at once!")
print("   This is what happens billions of times during training.")

Weight matrix W:
tensor([[-0.0288,  1.3421],
        [-0.7436, -0.9712],
        [-1.2922,  0.3337]])
Input: tensor([1.0000, 0.5000])
Prediction: tensor([ 0.6422, -1.2292, -1.1253])
Target: tensor([1., 0., 0.])
Loss: 2.9053

Gradients for W (∂Loss/∂W):
tensor([[-0.7156, -0.3578],
        [-2.4583, -1.2292],
        [-2.2507, -1.1253]])

☝️ PyTorch computed the gradient for all 6 weights at once!
   This is what happens billions of times during training.


### 🛑 Try It Yourself
1. Create a tensor `x = 5.0` with `requires_grad=True`
2. Compute `y = x³ - 4x² + x`
3. Call `y.backward()`
4. Print `x.grad`
5. Verify: `dy/dx = 3x² - 8x + 1` at `x=5` → `3(25) - 40 + 1 = 36`

In [47]:
#1
x = torch.tensor(5.0, requires_grad=True)
y = x**3 - 4*x**2 + x
y.backward()
print(x.grad)

tensor(36.)
