<a href="https://colab.research.google.com/github/anuragpandey4/dl/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
import time
import math

# Check if GPU is available
print(f"PyTorch version: {torch.__version__}")
print(f"GPU available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU name: {torch.cuda.get_device_name(0)}")
else:
    print("⚠️ No GPU detected. Go to Runtime → Change runtime type → GPU")
    print("   (Some demos will still work, just slower)")

print("\n✅ Setup complete! Ready to go.")

PyTorch version: 2.11.0+cu128
GPU available: True
GPU name: Tesla T4

✅ Setup complete! Ready to go.


In [3]:
# A scalar (0D Tensor)
x = torch.tensor(5.0)
x

tensor(5.)

In [4]:
# A vector (1D Tensor)
v = torch.tensor([1.0, 2.0, 3.0])
v

tensor([1., 2., 3.])

In [5]:
# A matrix (2D Tensor)
m = torch.tensor([[1, 2], [3, 4]])
m

tensor([[1, 2],
        [3, 4]])

In [6]:
# A 3D tensor (e.g., Batch x Height x Width)
t = torch.zeros(2, 3, 4) # shape [2, 3, 4]
t

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
# Check shape — you'll do this ALL the time
print(t.shape)

torch.Size([2, 3, 4])


In [8]:
a = torch.randn(3,4)
b = torch.randn(4,5)

In [9]:
a @ b

tensor([[-0.9202,  4.8013, -2.1564, -2.6077,  1.1714],
        [-0.5898, -1.7922,  3.1070,  5.6827, -1.5338],
        [ 0.2440,  0.8499, -0.9961,  0.1539,  0.2447]])

In [10]:
x = torch.randn(8,3,768)

In [11]:
x.dim()

3

In [12]:
x = x.view(24,768)

In [13]:
x.dim()

2

In [14]:
x = torch.randn(8,12,3,64)

In [15]:
y = x.permute(0,2,1,3)

In [16]:
y.shape

torch.Size([8, 3, 12, 64])

# autograd

In [17]:
x = torch.tensor(3.0, requires_grad=True)

In [18]:
y = x ** 2 + 3

In [19]:
y.backward()

In [20]:
x.grad

tensor(6.)

In [21]:
# A scalar — just a number
scalar = torch.tensor(42.0)
print(f"Scalar: {scalar}")
print(f"  Shape: {scalar.shape}")      # torch.Size([])
print(f"  Dimensions: {scalar.dim()}")  # 0
print()

# A vector — a list of numbers
vector = torch.tensor([1.0, 2.0, 3.0, 4.0])
print(f"Vector: {vector}")
print(f"  Shape: {vector.shape}")      # torch.Size([4])
print(f"  Dimensions: {vector.dim()}")  # 1
print()

# A matrix — a grid of numbers
matrix = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])
print(f"Matrix:\n{matrix}")
print(f"  Shape: {matrix.shape}")      # torch.Size([2, 3])
print(f"  Dimensions: {matrix.dim()}")  # 2
print()

# A 3D tensor — a cube of numbers
tensor_3d = torch.zeros(2, 3, 4)
print(f"3D Tensor shape: {tensor_3d.shape}")    # [2, 3, 4]
print(f"  Dimensions: {tensor_3d.dim()}")        # 3
print()

# A 4D tensor — like a batch going through multi-head attention
tensor_4d = torch.zeros(8, 12, 3, 64)
print(f"4D Tensor shape: {tensor_4d.shape}")    # [8, 12, 3, 64]
print(f"  That's: 8 sentences × 12 heads × 3 tokens × 64 dims")

Scalar: 42.0
  Shape: torch.Size([])
  Dimensions: 0

Vector: tensor([1., 2., 3., 4.])
  Shape: torch.Size([4])
  Dimensions: 1

Matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])
  Shape: torch.Size([2, 3])
  Dimensions: 2

3D Tensor shape: torch.Size([2, 3, 4])
  Dimensions: 3

4D Tensor shape: torch.Size([8, 12, 3, 64])
  That's: 8 sentences × 12 heads × 3 tokens × 64 dims


In [23]:
# Zeros and ones
z = torch.zeros(3, 4)        # 3×4 matrix of zeros
o = torch.ones(2, 5)         # 2×5 matrix of ones

# Random (normal distribution) — this is how weights start!
r = torch.randn(3, 3)        # random values, mean=0, std=1
print("Random matrix (this is how neural network weights begin):")
print(r)
print()

# From a range
seq = torch.arange(0, 10)    # [0, 1, 2, ..., 9]
print(f"Sequence: {seq}")

# Linspace — evenly spaced
lin = torch.linspace(0, 1, 5)  # 5 values from 0 to 1
print(f"Linspace: {lin}")

Random matrix (this is how neural network weights begin):
tensor([[ 0.7967,  1.8428,  0.2208],
        [-0.8487,  1.0205,  1.1880],
        [ 0.7008,  0.5786,  0.8023]])

Sequence: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Linspace: tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [24]:
# Real-world shapes in deep learning:
batch_size = 8
seq_len = 128
embed_dim = 768
num_heads = 12
head_dim = embed_dim // num_heads  # 64

# A batch of tokenized sentences
x = torch.randn(batch_size, seq_len, embed_dim)
print(f"Batch of sentences: {x.shape}")
print(f"  {batch_size} sentences, {seq_len} tokens each, {embed_dim} dimensions per token")
print()

# Reshape for multi-head attention
x_heads = x.view(batch_size, seq_len, num_heads, head_dim)
print(f"After splitting into heads: {x_heads.shape}")
print(f"  {batch_size} sentences, {seq_len} tokens, {num_heads} heads, {head_dim} dims per head")
print()

# Rearrange so heads come before tokens (needed for attention)
x_ready = x_heads.permute(0, 2, 1, 3)
print(f"After permute for attention: {x_ready.shape}")
print(f"  {batch_size} sentences, {num_heads} heads, {seq_len} tokens, {head_dim} dims")
print()
print("☝️ This is EXACTLY what happens inside every transformer!")

Batch of sentences: torch.Size([8, 128, 768])
  8 sentences, 128 tokens each, 768 dimensions per token

After splitting into heads: torch.Size([8, 128, 12, 64])
  8 sentences, 128 tokens, 12 heads, 64 dims per head

After permute for attention: torch.Size([8, 12, 128, 64])
  8 sentences, 12 heads, 128 tokens, 64 dims

☝️ This is EXACTLY what happens inside every transformer!
